### PR TITLE
Feature/mapping source generator

### PR DESCRIPTION
**Pull request by SSchulze1989**
## Feature description
This PR will add a source generator that can generate mapping code for automatically reading data from an iracing data buffer to a user defined class.

## How does this work?
The source generator looks for classes that have the `[AysdkoData]` attribute and generates a mapper class for each.
The mapper class has a single constructor that takes in the current list of variable headers.
After initializing the mapper a single instance of the user defined class can be directly created by calling `MapFromBuffer()` and providing the current iracing data buffer.

### CODE REVIEW

**Comment by AdrianJSClark** [comment]
This is pretty awesome! I feel like I want to tweak some of the naming, but not sure how.

Unfortunately at this minute I need to get some day job work done so I can continue to afford my iRacing subscription 😁, but will dive in to this more tonight after work. Thanks heaps!

**Comment by SSchulze1989** [comment]
@AdrianJSClark 
had some more fun with unit tests and so far it looks like its working together with your logic!
Also took the liberty to make a small change to the `VariableHeader` struct by marshalling the `Name`, `Description` and `Unit` directly to `string`.
In case you had a reason to use `char[]` i can revert this ofc.

**Comment by AdrianJSClark** [comment]
> @AdrianJSClark had some more fun with unit tests and so far it looks like its working together with your logic! Also took the liberty to make a small change to the `VariableHeader` struct by marshalling the `Name`, `Description` and `Unit` directly to `string`. In case you had a reason to use `char[]` i can revert this ofc.

I was only using `char[]` to match the iRacing SDK types, so that's fine.

**Comment by AdrianJSClark** [comment]
@SSchulze1989 I'm just going to merge this on to a separate branch. There's just some cleaning up I'd like to do around the source generator (some naming, code clean up, test clean up, building into a proper NuGet package, etc).

Having this stuff on it's own feature branch for now just allows me the mental space to do bits of work on the base package separately. Hope that's all cool!

**Pull request merged**
